baseURL = 'https://martin.vet/'
languageCode = 'en-us'
title = 'Martin McDowell vet locum'
theme = "mainroad"
googleAnalytics = "UA-90315878-1" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Martin McDowell MRCVS"
  bio = "Dr Martin McDowell DrVetMed ISFM AdvCertFB MRCVS - Locum veterinary surgeon for companion animals. Graduated vet school in 1998, worked in veterinary and non-veterinary industries. Vet work including permanent employment, locuming and clinical directorship."
  avatar = "img/Martin_on_Carriacou-300x300.jpg"

[Params]
  subtitle = "Providing locum services to veterinary practices around the UK." # Deprecated in favor of .Site.Params.logo.subtitle
  #description = "Locum veterinary surgeon for companion animals" # Site description. Used in meta description
  description = "Providing locum services to veterinary practices around the UK." # Site description. Used in meta description 
  copyright = "Martin.vet" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  # mainSections = ["index", "posts", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  mainSections = ["index"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  #googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  #highlightColor = "#e22d30" # Override highlight color
  highlightColor = "#d38412" # Override highlight color THIS is LIVE
  # highlightColor = "#3f3f3f" # Override highlight color - changed for HM 2022
  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "Roboto, 'Open Sans', Arial"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/martin-vet-square1.ai.svg" # Logo image. Path relative to "static"
  title = "Martin McDowell MRCVS" # Logo title, otherwise will use site title
  subtitle = "Small animal locum vet - Martin.vet" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  #widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  widgets = ["search", "recent", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  email = "me@martin.vet"
  #facebook = "username"
  #twitter = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "My personal blog"
  url = "https://blog.mcdowell.si/"
  icon = "svg/author.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "RCVS Find-a-vet Profile"
  url = "https://findavet.rcvs.org.uk/find-a-vet-surgeon/martin-mcdowell-6441157/"
  icon = "svg/author.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "Vetsurgeon.org Profile"
  url = "https://www.vetsurgeon.org/members/mcdragon"
  icon = "svg/author.svg" # Optional. Path relative to "layouts/partials"


[menu]

 [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -500
    
 [[menu.main]]
    name = "About me"
    post = ""
    pre = "<i class='fa fa-road'></i>"
    url = "/about/"
    weight = -400
    
  [[menu.main]]
    name = "Skills matrix"
    post = ""
    pre = "<i class='fa fa-road'></i>"
    url = "/skills-matrix/"
    weight = -300

  [[menu.main]]
    name = "Book me"
    post = ""
    pre = "<i class='fa fa-road'></i>"
    url = "/book-me/"
    weight = -200
